version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - myapp
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - myvol:/data/db
    ports:
      - '27018:27017'
    networks:
      - myapp

volumes:
  myvol:
    driver: local

networks:
  myapp:
    driver: bridge
